services:
  - type: web
    name: careerpath-backend
    env: docker
    region: singapore
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/courses
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: CareerPath
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://careerpath-backend.onrender.com
      - key: APP_KEY
        value: CHANGE_ME_LARAVEL_APP_KEY
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: careerpath-mysql-shajedulkabir106-f79a.b.aivencloud.com
      - key: DB_PORT
        value: "18232"
      - key: DB_DATABASE
        value: careerpath
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: CHANGE_ME_AIVEN_DB_PASSWORD
      - key: MYSQL_ATTR_SSL_CA
        value: /var/www/html/ca.pem
      - key: JWT_SECRET
        value: CHANGE_ME_JWT_SECRET
      - key: JWT_TTL_MINUTES
        value: "10080"
      - key: JWT_ISSUER
        value: https://careerpath-backend.onrender.com
      - key: GEMINI_API_KEY
        value: ""
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""
      - key: FILESTACK_API_KEY
        value: ""
